---
- hosts: rpi
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: upgrade packages
      apt:
        name: "*"
        state: latest

    - name: install prerequisites
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - lsb-release
        - software-properties-common

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ansible_distribution_release}} stable


    - name: install docker engine
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: assert docker active
      service:
        name: docker
        state: started
        enabled: true

    - name: add user 'pi' to group docker
      user:
        name: pi
        groups: docker
        append: yes
