---
- hosts: all
  become: true
  gather_facts: false
  vars:
    new_user: ansible
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  tasks:
    - name: Create ansible user
      user:
        name: "{{ new_user }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        shell: /bin/bash
    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ copy_local_key }}"
    - name: permisisons
      copy:
        dest: /etc/sudoers.d/10-ansible
        content: |
          # User rules for ansible
          ansible ALL=(ALL) NOPASSWD:ALL



